create database  [NICESTORE2]
USE [NICESTORE2]
GO
/****** Object:  Table [dbo].[CHAT_LIEU]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHAT_LIEU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Ma_Chat_Lieu] [nvarchar](50) NULL,
	[Ten_Chat_Lieu] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_CHAT_LIEU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DE_GIAY]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DE_GIAY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_DE_GIAY] [nvarchar](50) NULL,
	[TEN_DE_GIAY] [nvarchar](50) NOT NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [nvarchar](50) NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_DE_GIAY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIA_CHI]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIA_CHI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_KH] [int] NOT NULL,
	[DIA_CHI_CU_THE] [nvarchar](50) NULL,
	[PHUONG_XA] [nvarchar](50) NULL,
	[QUAN_HUYEN] [nvarchar](50) NULL,
	[TINH_THANH] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_DIA_CHI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GIO_HANG]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIO_HANG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_KH] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_GIO_HANG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GIO_HANG_CT]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIO_HANG_CT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CTSP] [int] NULL,
	[ID_GIO_HANG] [int] NULL,
	[SO_LUONG] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_GIO_HANG_CT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HINH_ANH]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HINH_ANH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_SPCT] [int] NULL,
	[URL] [nvarchar](max) NULL,
	[TRANG_THAI] [int] NOT NULL,
 CONSTRAINT [PK_HING_ANH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HINH_THUC_TT]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HINH_THUC_TT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_GIAO_DICH] [nvarchar](50) NULL,
	[HINH_THUC] [nvarchar](50) NULL,
	[MO_TA] [nvarchar](max) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_HINH_THUC_TT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOA_DON]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOA_DON](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_NV] [int] NULL,
	[ID_KH] [int] NULL,
	[MA_HD] [nvarchar](50) NULL,
	[ID_VOUCHER] [int] NULL,
	[DIA_CHI_NGUOI_NHAN] [nvarchar](max) NULL,
	[SDT] [varchar](15) NULL,
	[TEN_NGUOI_NHAN] [nvarchar](50) NULL,
	[GHI_CHU] [nvarchar](max) NULL,
	[TONG_TIEN] [money] NULL,
	[NGAY_TAO] [datetime] NULL,
	[TIEN_GIAM] [money] NULL,
	[TRANG_THAI] [int] NULL,
	[THANH_PHO] [nvarchar](max) NULL,
	[QUAN_HUYEN] [nvarchar](max) NULL,
	[PHUONG_XA] [nvarchar](max) NULL,
	[PHI_SHIP] [int] NULL,
	[LOAI_HOA_DON] [nvarchar](50) NULL,
 CONSTRAINT [PK_HOA_DON] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOA_DON_CT]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOA_DON_CT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_HOA_DON] [int] NULL,
	[ID_CTSP] [int] NULL,
	[SO_LUONG] [int] NULL,
	[DON_GIA] [money] NULL,
	[NGAY_TAO] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_HOA_DON-CT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_HANG]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TK] [int] NULL,
	[MA_KH] [nvarchar](50) NULL,
	[HO] [nvarchar](50) NULL,
	[TEN_DEM] [nvarchar](50) NULL,
	[TEN] [nvarchar](50) NULL,
	[GIOI_TINH] [int] NULL,
	[EMAIL] [nvarchar](50) NULL,
	[SDT] [int] NULL,
	[NGAY_SINH] [datetime] NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_KHACH_HANG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KICH_CO]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KICH_CO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_KICH_CO] [nvarchar](50) NULL,
	[SIZE] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_KICH_CO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICH_SU_HD]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICH_SU_HD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_HOA_DON] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_THANH_TOAN] [datetime] NULL,
	[TRANG-THAI] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loai_Giay]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loai_Giay](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ma_Loai_Giay] [nvarchar](50) NULL,
	[Ten_Loai_Giay] [nvarchar](50) NULL,
	[Ngay_Tao] [datetime] NULL,
	[Ngay_Sua] [date] NULL,
	[Trang_Thai] [int] NULL,
 CONSTRAINT [PK_Loai_Giay] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAU_SAC]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAU_SAC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_MAU_SAC] [nvarchar](50) NULL,
	[TEN_MAU_SAC] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_MAU_SAC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAN_VIEN]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAN_VIEN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TK] [int] NULL,
	[MA_NV] [nvarchar](50) NULL,
	[SDT] [int] NULL,
	[EMAIL] [nvarchar](50) NULL,
	[HO] [nvarchar](50) NULL,
	[TEN_DEM] [nvarchar](50) NULL,
	[TEN] [nvarchar](50) NULL,
	[GIOI_TINH] [int] NULL,
	[NGAY_SINH] [datetime] NULL,
	[DIA_CHI] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_NHAN_VIEN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[San_Pham]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[San_Pham](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Ma_San_Pham] [nvarchar](50) NULL,
	[Ten_SP] [nvarchar](50) NULL,
	[Ngay_Tao] [datetime] NULL,
	[Ngay_Sua] [datetime] NULL,
	[Trang_Thai] [int] NULL,
 CONSTRAINT [PK_San_Pham] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAN_PHAM_CT]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAN_PHAM_CT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_SP] [int] NULL,
	[ID_MAU_SAC] [int] NULL,
	[ID_THE_LOAI] [int] NULL,
	[ID_KICH_CO] [int] NULL,
	[ID_CHAT_LIEU] [int] NULL,
	[ID_DE_GIAY] [int] NULL,
	[ID_THUONG_HIEU] [int] NULL,
	[MA_SPCT] [nvarchar](50) NULL,
	[GIA_BAN] [money] NULL,
	[SO_LUONG] [int] NULL,
	[MO_TA] [nvarchar](max) NOT NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_SAN_PHAM_CT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAI_KHOAN]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAI_KHOAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[PASSWORD] [nvarchar](50) NULL,
	[ROLE] [nvarchar](50) NULL,
 CONSTRAINT [PK_TAI_KHOAN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THANH_TOAN]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THANH_TOAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_HOA_DON] [int] NULL,
	[ID_HINH_THUC_TT] [int] NULL,
	[MA_GIAO_DICH] [nvarchar](50) NULL,
	[MO_TA] [nvarchar](max) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_THANH_TOAN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THUONG_HIEU]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THUONG_HIEU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_THUONG_HIEU] [nvarchar](50) NULL,
	[TEN_THUONG_HIEU] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_THUONG_HIEU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VOUCHER]    Script Date: 31-10-2024 04:16:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VOUCHER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MA_VOUCHER] [nvarchar](50) NULL,
	[TEN] [nvarchar](50) NULL,
	[LOAI_VOUCHER] [nvarchar](50) NULL,
	[NGAY_BAT_DAU] [datetime] NULL,
	[NGAY_KET_THUC] [datetime] NULL,
	[GIA_TRI_MIN] [money] NULL,
	[GIA_TRI_MAX] [money] NULL,
	[SO_LUONG] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[NGAY_SUA] [datetime] NULL,
	[MO_TA] [nvarchar](max) NULL,
	[TRANG_THAI] [int] NULL,
 CONSTRAINT [PK_VOUCHER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIA_CHI]  WITH CHECK ADD  CONSTRAINT [FK_DIA_CHI_KH] FOREIGN KEY([ID_KH])
REFERENCES [dbo].[KHACH_HANG] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DIA_CHI] CHECK CONSTRAINT [FK_DIA_CHI_KH]
GO
ALTER TABLE [dbo].[GIO_HANG]  WITH CHECK ADD  CONSTRAINT [FK_GIO_HANG_KHACH_HANG] FOREIGN KEY([ID_KH])
REFERENCES [dbo].[KHACH_HANG] ([ID])
GO
ALTER TABLE [dbo].[GIO_HANG] CHECK CONSTRAINT [FK_GIO_HANG_KHACH_HANG]
GO
ALTER TABLE [dbo].[GIO_HANG_CT]  WITH CHECK ADD  CONSTRAINT [FK_GIO_HANG_CT_GIO_HANG] FOREIGN KEY([ID_GIO_HANG])
REFERENCES [dbo].[GIO_HANG] ([ID])
GO
ALTER TABLE [dbo].[GIO_HANG_CT] CHECK CONSTRAINT [FK_GIO_HANG_CT_GIO_HANG]
GO
ALTER TABLE [dbo].[GIO_HANG_CT]  WITH CHECK ADD  CONSTRAINT [FK_GIO_HANG_CT_SAN_PHAM_CT] FOREIGN KEY([ID_CTSP])
REFERENCES [dbo].[SAN_PHAM_CT] ([ID])
GO
ALTER TABLE [dbo].[GIO_HANG_CT] CHECK CONSTRAINT [FK_GIO_HANG_CT_SAN_PHAM_CT]
GO
ALTER TABLE [dbo].[HINH_ANH]  WITH CHECK ADD  CONSTRAINT [FK_HINH_ANH_SAN_PHAM_CT] FOREIGN KEY([ID_SPCT])
REFERENCES [dbo].[SAN_PHAM_CT] ([ID])
GO
ALTER TABLE [dbo].[HINH_ANH] CHECK CONSTRAINT [FK_HINH_ANH_SAN_PHAM_CT]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [FK_HOA_DON_KHACH_HANG] FOREIGN KEY([ID_KH])
REFERENCES [dbo].[KHACH_HANG] ([ID])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [FK_HOA_DON_KHACH_HANG]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [FK_HOA_DON_NHAN_VIEN] FOREIGN KEY([ID_NV])
REFERENCES [dbo].[NHAN_VIEN] ([ID])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [FK_HOA_DON_NHAN_VIEN]
GO
ALTER TABLE [dbo].[HOA_DON]  WITH CHECK ADD  CONSTRAINT [FK_HOA_DON_VOUCHER] FOREIGN KEY([ID_VOUCHER])
REFERENCES [dbo].[VOUCHER] ([ID])
GO
ALTER TABLE [dbo].[HOA_DON] CHECK CONSTRAINT [FK_HOA_DON_VOUCHER]
GO
ALTER TABLE [dbo].[HOA_DON_CT]  WITH CHECK ADD  CONSTRAINT [FK_HOA_DON_CT_HOA_DON] FOREIGN KEY([ID_HOA_DON])
REFERENCES [dbo].[HOA_DON] ([ID])
GO
ALTER TABLE [dbo].[HOA_DON_CT] CHECK CONSTRAINT [FK_HOA_DON_CT_HOA_DON]
GO
ALTER TABLE [dbo].[KHACH_HANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACH_HANG_TAI_KHOAN] FOREIGN KEY([ID_TK])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[KHACH_HANG] CHECK CONSTRAINT [FK_KHACH_HANG_TAI_KHOAN]
GO
ALTER TABLE [dbo].[LICH_SU_HD]  WITH CHECK ADD  CONSTRAINT [FK_LICH_SU_HD_HOA_DON] FOREIGN KEY([ID_HOA_DON])
REFERENCES [dbo].[HOA_DON] ([ID])
GO
ALTER TABLE [dbo].[LICH_SU_HD] CHECK CONSTRAINT [FK_LICH_SU_HD_HOA_DON]
GO
ALTER TABLE [dbo].[NHAN_VIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHAN_VIEN_TAI_KHOAN] FOREIGN KEY([ID_TK])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[NHAN_VIEN] CHECK CONSTRAINT [FK_NHAN_VIEN_TAI_KHOAN]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_CHAT_LIEU] FOREIGN KEY([ID_CHAT_LIEU])
REFERENCES [dbo].[CHAT_LIEU] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_CHAT_LIEU]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_DE_GIAY] FOREIGN KEY([ID_DE_GIAY])
REFERENCES [dbo].[DE_GIAY] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_DE_GIAY]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_KICH_CO] FOREIGN KEY([ID_KICH_CO])
REFERENCES [dbo].[KICH_CO] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_KICH_CO]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_Loai_Giay] FOREIGN KEY([ID_THE_LOAI])
REFERENCES [dbo].[Loai_Giay] ([Id])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_Loai_Giay]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_MAU_SAC] FOREIGN KEY([ID_MAU_SAC])
REFERENCES [dbo].[MAU_SAC] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_MAU_SAC]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_San_Pham] FOREIGN KEY([ID_SP])
REFERENCES [dbo].[San_Pham] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_San_Pham]
GO
ALTER TABLE [dbo].[SAN_PHAM_CT]  WITH CHECK ADD  CONSTRAINT [FK_SAN_PHAM_CT_THUONG_HIEU] FOREIGN KEY([ID_THUONG_HIEU])
REFERENCES [dbo].[THUONG_HIEU] ([ID])
GO
ALTER TABLE [dbo].[SAN_PHAM_CT] CHECK CONSTRAINT [FK_SAN_PHAM_CT_THUONG_HIEU]
GO
ALTER TABLE [dbo].[THANH_TOAN]  WITH CHECK ADD  CONSTRAINT [FK_THANH_TOAN_HINH_THUC_TT] FOREIGN KEY([ID_HINH_THUC_TT])
REFERENCES [dbo].[HINH_THUC_TT] ([ID])
GO
ALTER TABLE [dbo].[THANH_TOAN] CHECK CONSTRAINT [FK_THANH_TOAN_HINH_THUC_TT]
GO
ALTER TABLE [dbo].[THANH_TOAN]  WITH CHECK ADD  CONSTRAINT [FK_THANH_TOAN_HOA_DON] FOREIGN KEY([ID_HOA_DON])
REFERENCES [dbo].[HOA_DON] ([ID])
GO
ALTER TABLE [dbo].[THANH_TOAN] CHECK CONSTRAINT [FK_THANH_TOAN_HOA_DON]
GO

INSERT INTO [dbo].[VOUCHER] 
(MA_VOUCHER, TEN, LOAI_VOUCHER, NGAY_BAT_DAU, NGAY_KET_THUC, GIA_TRI_MIN, GIA_TRI_MAX, SO_LUONG, NGAY_TAO, NGAY_SUA, MO_TA, TRANG_THAI) 
VALUES 
(N'VOUCHER001', N'Giảm giá 10%', N'Phần trăm', '2024-11-01', '2024-11-30', 50000, 200000, 100, GETDATE(), GETDATE(), N'Voucher giảm 10% cho các đơn hàng trên 50,000', 1),
(N'VOUCHER002', N'Giảm giá 20%', N'Tiền mặt', '2024-11-01', '2024-12-31', 100000, 300000, 50, GETDATE(), GETDATE(), N'Voucher giảm giá trực tiếp 20,000', 1),
(N'VOUCHER003', N'Miễn phí vận chuyển', N'Tiền mặt', '2024-11-05', '2024-12-05', 0, 50000, 200, GETDATE(), GETDATE(), N'Voucher miễn phí vận chuyển với đơn trên 50,000', 1),
(N'VOUCHER004', N'Giảm giá 15%', N'Phần trăm', '2024-11-10', '2024-11-30', 70000, 250000, 150, GETDATE(), GETDATE(), N'Voucher giảm 15% cho khách hàng VIP', 1),
(N'VOUCHER005', N'Giảm 30,000 cho đơn trên 100,000', N'Tiền mặt', '2024-11-15', '2024-12-15', 100000, 1000000, 75, GETDATE(), GETDATE(), N'Voucher giảm 30,000 cho đơn hàng trên 100,000', 1);


INSERT INTO [dbo].[Loai_Giay] (Ma_Loai_Giay, Ten_Loai_Giay, Ngay_Tao, Ngay_Sua, Trang_Thai) 
VALUES 
(N'LG001', N'Sneaker', GETDATE(), NULL, 1),
(N'LG002', N'Sandals', GETDATE(), NULL, 1),
(N'LG003', N'Boots', GETDATE(), NULL, 1),
(N'LG004', N'Loafer', GETDATE(), NULL, 1),
(N'LG005', N'Oxford', GETDATE(), NULL, 0);

INSERT INTO [dbo].[Loai_Giay] ([Ma_Loai_Giay], [Ten_Loai_Giay], [Ngay_Tao], [Ngay_Sua], [Trang_Thai])
VALUES
    ('LG001', 'Giày Thể Thao', GETDATE(), GETDATE(), 1),
    ('LG002', 'Giày Dây', GETDATE(), GETDATE(), 1),
    ('LG003', 'Giày Slip-On', GETDATE(), GETDATE(), 1),
    ('LG004', 'Giày Bóng Đá', GETDATE(), GETDATE(), 1),
    ('LG005', 'Giày Sandal', GETDATE(), GETDATE(), 1);

	INSERT INTO [dbo].[CHAT_LIEU] ([Ma_Chat_Lieu], [Ten_Chat_Lieu], [NGAY_TAO], [NGAY_SUA], [TRANG_THAI])
VALUES
    ('CL001', 'Vải Cotton', GETDATE(), GETDATE(), 1),
    ('CL002', 'Da Tổng Hợp', GETDATE(), GETDATE(), 1),
    ('CL003', 'Nhung', GETDATE(), GETDATE(), 1),
    ('CL004', 'Chất Liệu Nylon', GETDATE(), GETDATE(), 1),
    ('CL005', 'Vải Lụa', GETDATE(), GETDATE(), 1);
